export enum authConstants {
    AUTHORIZATION_GET_USER = "AUTHORIZATION_GET_USER",
    GET_PERMISSIONS = "AUTHORIZATION_GET_PERMISSION",
    GET_TOKEN = "AUTHORIZATION_GET_TOKEN",
    ERROR = "AUTHORIZATION_ERROR",
    REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
    REGISTER_USER_LOADING = "REGISTER_USER_LOADING",
    REGISTER_USER_ERROR = "REGISTER_USER_ERROR",
    REGISTER_USER_NOTIFICATION_RESET = "REGISTER_USER_NOTIFICATION_RESET",
    LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS",
    LOGIN_USER_LOADING = "LOGIN_USER_LOADING",
    LOGIN_USER_ERROR = "LOGIN_USER_ERROR",
    LOGIN_USER_NOTIFICATION_RESET = "LOGIN_USER_NOTIFICATION_RESET",
    NOTIFICATION_RESET = "NOTIFICATION_RESET"
}